Catkin-ProjectName: qt_ros
Version: 0.1.4
Description: This stack provides templates, tutorials and other resources that assist qt on ros development.
Author: Daniel Stonier <d.stonier@gmail.com>
Maintainer: Daniel Stonier <d.stonier@gmail.com>
Homepage: http://ros.org/wiki/qt_ros

Depends: catkin, std_msgs, ros_comm, libqt4-dev, qt4-dev-tools

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
#Catkin-ROS-Message-Generator: cpp

